import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/ProductListingPage.module.css";
import Link from "next/link";
import { createPath } from "@/lib/helpers";

export default function ProductListingPage({ products }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.list}>
          {products.map((producto) => {
            const { brand, id, image, skus } = producto;
            return (
              <Link key={id} href={createPath(id, brand)}>
                <div>
                  <h3>{brand}</h3>
                  <Image
                    src={image}
                    width={300}
                    height={500}
                    alt="producto"
                    priority
                  />
                </div>
              </Link>
            );
          })}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/products");
  const data = await res.json();

  return {
    props: {
      products: data,
    },
  };
}
